import { defineComponents } from "blume";

export default defineComponents({
  islands: {
    AgentChatPreview: "./demos/agent-chat-preview.tsx",
    AnimatedWashPlayground: "./demos/animated-wash-playground.tsx",
    AnimatedWashPreview: "./demos/animated-wash-preview.tsx",
    AppCardPreview: "./demos/app-card-preview.tsx",
    AppCardShaderPreview: "./demos/app-card-shader-preview.tsx",
    AppCreatorPreview: "./demos/app-creator-preview.tsx",
    AuthFormCoverPreview: "./demos/auth-form-cover-preview.tsx",
    AuthFormPreview: "./demos/auth-form-preview.tsx",
    ChatInputPreview: "./demos/chat-input-preview.tsx",
    ChatMessagePreview: "./demos/chat-message-preview.tsx",
    ChatWorkingPreview: "./demos/chat-working-preview.tsx",
    CheckpointTimelinePreview: "./demos/checkpoint-timeline-preview.tsx",
    ColorPickerPreview: "./demos/color-picker-preview.tsx",
    ConfirmDialogPreview: "./demos/confirm-dialog-preview.tsx",
    EmptyStatePreview: "./demos/empty-state-preview.tsx",
    MetricCardDeltaVariants: "./demos/metric-card-delta-variants.tsx",
    MetricCardFormatVariants: "./demos/metric-card-format-variants.tsx",
    MetricCardPreview: "./demos/metric-card-preview.tsx",
    MetricCardSystemVariants: "./demos/metric-card-system-variants.tsx",
    ModelSelectPreview: "./demos/model-select-preview.tsx",
    NeonAuroraPlayground: "./demos/neon-aurora-playground.tsx",
    NeonLoaderPreview: "./demos/neon-loader-preview.tsx",
    PreviewFramePreview: "./demos/preview-frame-preview.tsx",
    ProvisioningStatusPreview: "./demos/provisioning-status-preview.tsx",
    StatusBadgePreview: "./demos/status-badge-preview.tsx",
    ThemePaster: "./demos/theme-paster.tsx",
    ThinkingModelSelectPreview: "./demos/thinking-model-select-preview.tsx",
    ThinkingSelectPreview: "./demos/thinking-select-preview.tsx",
    ToolCallChipPreview: "./demos/tool-call-chip-preview.tsx",
    WorkspaceTabsPreview: "./demos/workspace-tabs-preview.tsx",
  },
});
