import { defineComponents } from "blume";

import Header from "./components/blume/header.astro";

export default defineComponents({
  islands: {
    ActivityFeedPreview: "./demos/activity-feed-preview.tsx",
    AgentChatPreview: "./demos/agent-chat-preview.tsx",
    AnimatedWashPlayground: "./demos/animated-wash-playground.tsx",
    AnimatedWashPreview: "./demos/animated-wash-preview.tsx",
    ApiKeyListPreview: "./demos/api-key-list-preview.tsx",
    AppCardPreview: "./demos/app-card-preview.tsx",
    AppCardShaderPreview: "./demos/app-card-shader-preview.tsx",
    AppCreatorPreview: "./demos/app-creator-preview.tsx",
    AuthFormCoverPreview: "./demos/auth-form-cover-preview.tsx",
    AuthFormPreview: "./demos/auth-form-preview.tsx",
    AutoscaleChartPreview: "./demos/autoscale-chart-preview.tsx",
    BannerPatternPlayground: "./demos/banner-pattern-playground.tsx",
    BranchPickerPreview: "./demos/branch-picker-preview.tsx",
    BranchTreePreview: "./demos/branch-tree-preview.tsx",
    ChainOfThoughtPreview: "./demos/chain-of-thought-preview.tsx",
    ChangelogTimeline: "./demos/changelog-timeline.tsx",
    ChatInputPreview: "./demos/chat-input-preview.tsx",
    ChatMessagePreview: "./demos/chat-message-preview.tsx",
    ChatWorkingPreview: "./demos/chat-working-preview.tsx",
    CheckpointTimelinePreview: "./demos/checkpoint-timeline-preview.tsx",
    ColorPickerPreview: "./demos/color-picker-preview.tsx",
    ComputeStatusPreview: "./demos/compute-status-preview.tsx",
    ComputeStatusStateVariants: "./demos/compute-status-state-variants.tsx",
    ConfirmDialogPreview: "./demos/confirm-dialog-preview.tsx",
    CreateProjectPreview: "./demos/create-project-preview.tsx",
    DBConnectionCardPreview: "./demos/db-connection-card-preview.tsx",
    DateRangePickerPreview: "./demos/date-range-picker-preview.tsx",
    DotMatrixWavePlayground: "./demos/dot-matrix-wave-playground.tsx",
    EmptyStatePreview: "./demos/empty-state-preview.tsx",
    HalftoneBloomPlayground: "./demos/halftone-bloom-playground.tsx",
    HealthCardPreview: "./demos/health-card-preview.tsx",
    HealthCardStatusVariants: "./demos/health-card-status-variants.tsx",
    InlineCitationPreview: "./demos/inline-citation-preview.tsx",
    MeshGradientPlayground: "./demos/mesh-gradient-playground.tsx",
    MetricCardDeltaVariants: "./demos/metric-card-delta-variants.tsx",
    MetricCardFormatVariants: "./demos/metric-card-format-variants.tsx",
    MetricCardPreview: "./demos/metric-card-preview.tsx",
    MetricCardSystemVariants: "./demos/metric-card-system-variants.tsx",
    ModelSelectPreview: "./demos/model-select-preview.tsx",
    NeonAuroraPlayground: "./demos/neon-aurora-playground.tsx",
    NeonLoaderPreview: "./demos/neon-loader-preview.tsx",
    PreviewFramePreview: "./demos/preview-frame-preview.tsx",
    ProvisioningStatusPreview: "./demos/provisioning-status-preview.tsx",
    ReasoningPreview: "./demos/reasoning-preview.tsx",
    RegionCardPreview: "./demos/region-card-preview.tsx",
    RegionGlobePreview: "./demos/region-globe-preview.tsx",
    RegionSelectPreview: "./demos/region-select-preview.tsx",
    StatusBadgePreview: "./demos/status-badge-preview.tsx",
    ThemePaster: "./demos/theme-paster.tsx",
    ThinkingModelSelectPreview: "./demos/thinking-model-select-preview.tsx",
    ThinkingSelectPreview: "./demos/thinking-select-preview.tsx",
    ToolCallChipPreview: "./demos/tool-call-chip-preview.tsx",
    UpgradeDialogPreview: "./demos/upgrade-dialog-preview.tsx",
    UsageCardMetricVariants: "./demos/usage-card-metric-variants.tsx",
    UsageCardPreview: "./demos/usage-card-preview.tsx",
    UsagePanelPreview: "./demos/usage-panel-preview.tsx",
    WorkspaceTabsPreview: "./demos/workspace-tabs-preview.tsx",
  },
  layout: { Header },
});
